development:
  adapter: postgresql
  encoding: unicode
  database: icogoldrush
  pool: 5
  timeout: 5000
  username:
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: icogoldrush_test
  pool: 5
  timeout: 5000
  username:
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: icogoldrush_production
  pool: 5
  timeout: 5000
  username:
  host: localhost
  port: 5432
